### ISSUE TITLE
Needs Update

### ISSUE THREAD

**Issue by Satava** [mehanic321/Stationeers.NormalQuarry#3]
No longer working with current version of Addon Loader & Game Client.

**Comment by Dean-Gallagher** [comment]
yup need to be updated but seems to be abadonware

**Comment by mehanic321** [comment]
thanks for the suggestion, now a lot of work, I can update later.:)

**Comment by Satava** [comment]
> thanks for the suggestion, now a lot of work, I can update later.:)

Thanks mehanic321. Am looking forward to the update. This was a brilliant addon and I hope to see it working again.

**Comment by mehanic321** [comment]
Выполнен! 
Performed! 
:)

**Comment by Satava** [comment]
Thank you very much! I'll give it a try tonight and see how it works.

Большое спасибо! Я попробую сегодня вечером и посмотрю, как это работает.
